version: '3'
services:
  postgres_db:
    image: postgres:latest
    container_name: post_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_db:/var/lib/postgresql/data

  fast_back:
    container_name: fast_backend
    build:
      context: .
      dockerfile: ./Dockerfile

    command: uvicorn main:app --host 0.0.0.0
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres_db:5432/
    volumes:
      - .:/test_app
    ports:
      - '8000:8000'
    depends_on:
      - postgres_db


volumes:
  postgres_db:
    driver: local
